dfghj

diff --git a/basics/2-bring_me_home b/basics/2-bring_me_home
--- a/basics/2-bring_me_home
+++ b/basics/2-bring_me_home
@@ -1,2 +1,2 @@
 #!/bin/bash
-echo "$(cd)"
+cd /root || { echo "Failed to change directory to /root"; exit 1; }
